<a href="https://colab.research.google.com/github/si1242/machine_leraning_experiments/blob/master/random_seed_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Simple experiment for ML Random Seed


In [0]:
import numpy as np
import pandas as pd

In [0]:
# fix Numpy seed
np.random.seed(42)

## You need to fix seed again after execute np.random method

In [4]:
print(np.random.randint(0, 1000, 10))

[102 435 860 270 106  71 700  20 614 121]


In [5]:
print(np.random.randint(0, 1000, 10))

[466 214 330 458  87 372  99 871 663 130]


In [7]:
# You need to fix seed again after np.random method
np.random.seed(42)
print(np.random.randint(0, 1000, 10))

[102 435 860 270 106  71 700  20 614 121]


## In Pandas, you need to set the seed value each time

In [19]:
df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, 2, 1, 8]},
                  index=['falcon', 'dog', 'spider', 'fish'])
df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [12]:
df['num_legs'].sample(n=3)

dog       4
falcon    2
fish      0
Name: num_legs, dtype: int64

In [13]:
df['num_legs'].sample(n=3)

fish      0
dog       4
falcon    2
Name: num_legs, dtype: int64

In [15]:
df['num_legs'].sample(n=3, random_state=1)

fish      0
spider    8
falcon    2
Name: num_legs, dtype: int64

In [17]:
# reproducible
df['num_legs'].sample(n=3, random_state=1)

fish      0
spider    8
falcon    2
Name: num_legs, dtype: int64

In [18]:
# non-reproducible
df['num_legs'].sample(n=3)

falcon    2
spider    8
dog       4
Name: num_legs, dtype: int64

## If you set Numpy random seed, you don't need to set Pandas random_state separately.


In [26]:
s = pd.Series(np.arange(100))
s

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int64

In [27]:
np.random.seed(42)

s.sample(n=3)

83    83
53    53
70    70
dtype: int64

In [28]:
s.sample(n=3, random_state=42)

83    83
53    53
70    70
dtype: int64

In [29]:
np.random.seed(2020)

s.sample(n=3)

43    43
12    12
93    93
dtype: int64

In [30]:
s.sample(n=3, random_state=2020)

43    43
12    12
93    93
dtype: int64